spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Store
    username: postgres
    password: password

  jpa:
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: db/dbchangelog.yaml

logging:
  level:
    org:
      hibernate:
        SQL: debug

bucket:
  name: ${StoreBucketName}