spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/dbchangelog.yaml
    enabled: true
    default-schema: public
    drop-first: true

  jpa:
    hibernate:
      ddl-auto: validate

bucket:
  name: ${StoreBucketName}